# Generated by Django 3.2.7 on 2021-10-07 01:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='External Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation datetime', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Update datetime', null=True, verbose_name='Updated at')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is superuser?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ('created_at',),
            },
        ),
    ]
