# Generated by Django 3.2.7 on 2021-10-07 01:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('internet_speed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='External Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation datetime', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Update datetime', null=True, verbose_name='Updated at')),
                ('download_speed', models.FloatField(default=0)),
                ('upload_speed', models.FloatField(default=0)),
                ('ping', models.FloatField(default=0)),
                ('image_url', models.URLField(default='')),
            ],
            options={
                'db_table': 'internet',
                'ordering': ('created_at',),
            },
        ),
    ]
